## 병렬처리 이전 코드

In [1]:
import os
import re
import time
import random
import pandas as pd
from openai import OpenAI

# =========================================================
# 0. OpenAI client
# =========================================================
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [2]:
# =========================================================
# 1. 기본 설정
# =========================================================
MODEL_NAME = "gpt-5.4"   # 사용 가능한 모델명으로 변경 가능
RANDOM_STATE = 42
random.seed(RANDOM_STATE)

TARGET_PER_TOPIC = 10_000
BATCH_DOCS = 20
SAVE_EVERY = 5

OUTPUT_DIR = "../data/processed/ai"
os.makedirs(OUTPUT_DIR, exist_ok=True)

topic_info = {
    "320": {
        "topic_name": "경제학",
        "prompt_topic": "경제학 개념, 시장, 정책, 소비, 생산, 분배, 금융, 경기 등과 관련된 설명형 글"
    },
    "360": {
        "topic_name": "법률·법학",
        "prompt_topic": "법, 제도, 권리, 의무, 판례, 책임, 절차, 규범 등과 관련된 설명형 글"
    },
    "370": {
        "topic_name": "교육학",
        "prompt_topic": "학습, 교육과정, 교수법, 평가, 학교, 발달, 교육환경 등과 관련된 설명형 글"
    },
    "400": {
        "topic_name": "자연과학",
        "prompt_topic": "자연 현상, 생명, 물질, 에너지, 실험, 관찰, 과학 원리 등과 관련된 설명형 글"
    },
    "440": {
        "topic_name": "천문학",
        "prompt_topic": "우주, 행성, 별, 은하, 중력, 천체 관측, 우주 현상 등과 관련된 설명형 글"
    },
}

STYLE_POOL = [
    "개념 설명 중심",
    "원리 설명 중심",
    "사례를 곁들인 설명",
    "비교·대조 중심",
    "입문서 스타일의 설명",
]

LENGTH_POOL = [
    "4~6문장",
    "5~7문장",
    "6~8문장",
]

TEMPERATURE_POOL = [0.7, 0.9, 1.0]

In [3]:
# =========================================================
# 2. 텍스트 처리 함수
# =========================================================

def normalize_text(text):
    if text is None:
        return ""
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    text = text.replace("“", '"').replace("”", '"').replace("’", "'").replace("‘", "'")
    return text

def split_sentences_korean(text):
    text = normalize_text(text)
    text = text.replace("\n", " ")
    sents = re.split(r'(?<=[\.\?\!])\s+', text)

    if len(sents) == 1:
        sents = re.split(r'(?<=다)\s+|(?<=요)\s+|(?<=니다)\s+', text)

    return [s.strip() for s in sents if s.strip()]

def is_valid_sentence(text, min_words=5, max_words=50):
    text = normalize_text(text)

    if not text:
        return False
    if len(text) < 10:
        return False
    if not re.search(r"[가-힣]", text):
        return False

    word_count = len(text.split())
    if word_count < min_words or word_count > max_words:
        return False

    hangul_chars = re.findall(r"[가-힣]", text)
    if len(hangul_chars) / max(len(text), 1) < 0.3:
        return False

    meta_patterns = [
        r"^제\s*\d+\s*장",
        r"^제\s*\d+\s*절",
        r"^\d+\.$",
        r"^\d+\)",
        r"^부록",
        r"^참고문헌",
        r"^목차",
        r"^저자",
        r"^출판사",
        r"^ISBN",
        r"^머리말",
        r"^서문",
        r"^차례",
    ]
    for pattern in meta_patterns:
        if re.search(pattern, text):
            return False

    return True

def clean_ai_sentences(sentences):
    cleaned = []
    seen = set()

    for sent in sentences:
        sent = normalize_text(sent)
        sent = re.sub(r'^\s*[-•\d\.\)\(]+\s*', '', sent).strip()

        if is_valid_sentence(sent):
            if sent not in seen:
                cleaned.append(sent)
                seen.add(sent)

    return cleaned

In [4]:
# =========================================================
# 3. 프롬프트 및 생성 함수
# =========================================================

def make_generation_prompt(topic_name, topic_desc, style, length_spec, batch_docs):
    prompt = f"""
다음 조건에 맞는 한국어 설명문 여러 개를 작성하시오.

[분야]
{topic_name}

[세부 주제 범위]
{topic_desc}

[문체]
- 자연스러운 설명문 형태
- 지나치게 문학적이거나 대화체인 문장은 피할 것
- 불필요한 제목이나 메모는 쓰지 말 것
- 동일 표현 반복을 피할 것

[스타일]
{style}

[길이]
각 글은 {length_spec}

[출력 형식]
- 서로 다른 짧은 글 {batch_docs}개를 생성할 것
- 각 글은 1, 2, 3 ... 번호를 붙여 구분할 것
- 각 글은 하나의 짧은 문단 형태로 작성할 것
- 반드시 한국어만 사용할 것
"""
    return prompt.strip()

def generate_batch_text(topic_name, topic_desc, batch_docs=BATCH_DOCS):
    style = random.choice(STYLE_POOL)
    length_spec = random.choice(LENGTH_POOL)
    temperature = random.choice(TEMPERATURE_POOL)

    prompt = make_generation_prompt(
        topic_name=topic_name,
        topic_desc=topic_desc,
        style=style,
        length_spec=length_spec,
        batch_docs=batch_docs
    )

    response = client.responses.create(
        model=MODEL_NAME,
        input=prompt,
        temperature=temperature
    )

    text = getattr(response, "output_text", None)
    if not text:
        raise ValueError("응답에서 output_text를 찾지 못했다.")

    return text, {
        "style": style,
        "length_spec": length_spec,
        "temperature": temperature
    }

def split_generated_documents(raw_text):
    raw_text = normalize_text(raw_text)
    parts = re.split(r'\s*(?=\d+\.\s)', raw_text)

    docs = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        part = re.sub(r'^\d+\.\s*', '', part).strip()
        if part:
            docs.append(part)

    if len(docs) <= 1:
        docs = [x.strip() for x in raw_text.split("\n") if x.strip()]

    return docs

In [5]:
# =========================================================
# 4. 저장 파일명 함수
# =========================================================

def get_temp_save_path(topic_code, batch_num):
    return os.path.join(OUTPUT_DIR, f"ai_{topic_code}_temp_until_batch_{batch_num}.csv")

def get_final_save_path(topic_code, target_n):
    if target_n == 10_000:
        return os.path.join(OUTPUT_DIR, f"ai_{topic_code}_sampled_100k.csv")
    return os.path.join(OUTPUT_DIR, f"ai_{topic_code}_sampled_{target_n}.csv")

In [6]:
# =========================================================
# 5. 주제 하나 실행
# =========================================================

def build_ai_topic_dataset(topic_code, target_n=10_000, save_every=5, batch_docs=BATCH_DOCS):
    topic_name = topic_info[topic_code]["topic_name"]
    topic_desc = topic_info[topic_code]["prompt_topic"]

    print(f"\n===== {topic_name} ({topic_code}) AI 데이터 생성 시작 =====")

    all_rows = []
    seen_sentences = set()
    batch_num = 0

    while len(all_rows) < target_n:
        batch_num += 1

        try:
            raw_text, meta = generate_batch_text(topic_name, topic_desc, batch_docs=batch_docs)
            docs = split_generated_documents(raw_text)

            batch_rows = []

            for doc_idx, doc in enumerate(docs, start=1):
                sentences = split_sentences_korean(doc)
                cleaned_sents = clean_ai_sentences(sentences)

                for sent in cleaned_sents:
                    if sent not in seen_sentences:
                        batch_rows.append({
                            "text": sent,
                            "topic_code": topic_code,
                            "topic_name": topic_name,
                            "source": "ai",
                            "generation_style": meta["style"],
                            "length_spec": meta["length_spec"],
                            "temperature": meta["temperature"],
                            "batch_num": batch_num,
                            "doc_in_batch": doc_idx,
                            "word_count": len(sent.split())
                        })
                        seen_sentences.add(sent)

            if batch_rows:
                all_rows.extend(batch_rows)

            print(f"[{topic_name}] batch={batch_num} | 누적 문장 수={len(all_rows):,}")

            if batch_num % save_every == 0:
                temp_df = pd.DataFrame(all_rows)
                temp_path = get_temp_save_path(topic_code, batch_num)
                temp_df.to_csv(temp_path, index=False, encoding="utf-8-sig")
                print(f"중간 저장 완료 -> {temp_path}")

            time.sleep(0.8)

        except Exception as e:
            print(f"[오류] batch={batch_num}, error={e}")
            time.sleep(3)

    final_df = pd.DataFrame(all_rows).head(target_n).copy()
    final_df = final_df.drop_duplicates(subset=["text"]).reset_index(drop=True)

    while len(final_df) < target_n:
        needed = target_n - len(final_df)
        print(f"[{topic_name}] 중복 제거 후 부족분 {needed:,}개 추가 생성")

        try:
            raw_text, meta = generate_batch_text(topic_name, topic_desc, batch_docs=batch_docs)
            docs = split_generated_documents(raw_text)

            new_rows = []
            existing = set(final_df["text"].tolist())

            for doc_idx, doc in enumerate(docs, start=1):
                sentences = split_sentences_korean(doc)
                cleaned_sents = clean_ai_sentences(sentences)

                for sent in cleaned_sents:
                    if sent not in existing:
                        new_rows.append({
                            "text": sent,
                            "topic_code": topic_code,
                            "topic_name": topic_name,
                            "source": "ai",
                            "generation_style": meta["style"],
                            "length_spec": meta["length_spec"],
                            "temperature": meta["temperature"],
                            "batch_num": batch_num,
                            "doc_in_batch": doc_idx,
                            "word_count": len(sent.split())
                        })
                        existing.add(sent)

            if new_rows:
                final_df = pd.concat([final_df, pd.DataFrame(new_rows)], axis=0).reset_index(drop=True)
                final_df = final_df.drop_duplicates(subset=["text"]).reset_index(drop=True)

            time.sleep(0.8)

        except Exception as e:
            print(f"[부족분 생성 오류] {e}")
            time.sleep(3)

    final_df = final_df.head(target_n).copy()

    final_path = get_final_save_path(topic_code, target_n)
    final_df.to_csv(final_path, index=False, encoding="utf-8-sig")

    print(f"===== {topic_name} 최종 완료: {len(final_df):,}문장 =====")
    print(f"최종 저장 완료 -> {final_path}")

    return final_df

### 경제학(320)

In [7]:
# =========================================================
# 6. 실행 예시
# =========================================================

# 경제학만 실행
df_ai_320 = build_ai_topic_dataset(topic_code="320", target_n=100_000, save_every=5)

===== 경제학 (320) AI 데이터 생성 시작 =====
[경제학] batch=1 | 누적 문장 수=80
[경제학] batch=2 | 누적 문장 수=159
[경제학] batch=3 | 누적 문장 수=278
[경제학] batch=4 | 누적 문장 수=357
[경제학] batch=5 | 누적 문장 수=437
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_5.csv
[경제학] batch=6 | 누적 문장 수=512
[경제학] batch=7 | 누적 문장 수=629
[경제학] batch=8 | 누적 문장 수=706
[경제학] batch=9 | 누적 문장 수=799
[경제학] batch=10 | 누적 문장 수=939
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_10.csv
[경제학] batch=11 | 누적 문장 수=1,015
[경제학] batch=12 | 누적 문장 수=1,115
[경제학] batch=13 | 누적 문장 수=1,194
[경제학] batch=14 | 누적 문장 수=1,264
[경제학] batch=15 | 누적 문장 수=1,359
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_15.csv
[경제학] batch=16 | 누적 문장 수=1,446
[경제학] batch=17 | 누적 문장 수=1,565
[경제학] batch=18 | 누적 문장 수=1,641
[경제학] batch=19 | 누적 문장 수=1,759
[경제학] batch=20 | 누적 문장 수=1,874
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_20.csv
[경제학] batch=21 | 누적 문장 수=1,949
[경제학] batch=22 | 누적 문장 수=2,064
[경제학] batch=23 | 누적 문장 수=2,137
[경제학] batch=24 | 누적 문장 수=2,235
[경제학] batch=25 | 누적 문장 수=2,312
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_25.csv
[경제학] batch=26 | 누적 문장 수=2,388
[경제학] batch=27 | 누적 문장 수=2,502
[경제학] batch=28 | 누적 문장 수=2,614
[경제학] batch=29 | 누적 문장 수=2,744
[경제학] batch=30 | 누적 문장 수=2,817
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_30.csv
[경제학] batch=31 | 누적 문장 수=2,933
[경제학] batch=32 | 누적 문장 수=2,998
[경제학] batch=33 | 누적 문장 수=3,073
[경제학] batch=34 | 누적 문장 수=3,160
[경제학] batch=35 | 누적 문장 수=3,235
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_35.csv
[경제학] batch=36 | 누적 문장 수=3,345
[경제학] batch=37 | 누적 문장 수=3,458
[경제학] batch=38 | 누적 문장 수=3,576
[경제학] batch=39 | 누적 문장 수=3,664
[경제학] batch=40 | 누적 문장 수=3,771
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_40.csv
[경제학] batch=41 | 누적 문장 수=3,881
[경제학] batch=42 | 누적 문장 수=3,975
[경제학] batch=43 | 누적 문장 수=4,089
[경제학] batch=44 | 누적 문장 수=4,215
[경제학] batch=45 | 누적 문장 수=4,280
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_45.csv
[경제학] batch=46 | 누적 문장 수=4,383
[경제학] batch=47 | 누적 문장 수=4,510
[경제학] batch=48 | 누적 문장 수=4,620
[경제학] batch=49 | 누적 문장 수=4,737
[경제학] batch=50 | 누적 문장 수=4,807
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_50.csv
[경제학] batch=51 | 누적 문장 수=4,913
[경제학] batch=52 | 누적 문장 수=5,025
[경제학] batch=53 | 누적 문장 수=5,112
[경제학] batch=54 | 누적 문장 수=5,200
[경제학] batch=55 | 누적 문장 수=5,313
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_55.csv
[경제학] batch=56 | 누적 문장 수=5,379
[경제학] batch=57 | 누적 문장 수=5,489
[경제학] batch=58 | 누적 문장 수=5,553
[경제학] batch=59 | 누적 문장 수=5,622
[경제학] batch=60 | 누적 문장 수=5,691
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_60.csv
[경제학] batch=61 | 누적 문장 수=5,790
[경제학] batch=62 | 누적 문장 수=5,877
[경제학] batch=63 | 누적 문장 수=5,947
[경제학] batch=64 | 누적 문장 수=6,014
[경제학] batch=65 | 누적 문장 수=6,091
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_65.csv
[경제학] batch=66 | 누적 문장 수=6,162
[경제학] batch=67 | 누적 문장 수=6,270
[경제학] batch=68 | 누적 문장 수=6,381
[경제학] batch=69 | 누적 문장 수=6,457
[경제학] batch=70 | 누적 문장 수=6,565
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_70.csv
[경제학] batch=71 | 누적 문장 수=6,682
[경제학] batch=72 | 누적 문장 수=6,775
[경제학] batch=73 | 누적 문장 수=6,847
[경제학] batch=74 | 누적 문장 수=6,919
[경제학] batch=75 | 누적 문장 수=7,024
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_75.csv
[경제학] batch=76 | 누적 문장 수=7,144
[경제학] batch=77 | 누적 문장 수=7,206
[경제학] batch=78 | 누적 문장 수=7,268
[경제학] batch=79 | 누적 문장 수=7,350
[경제학] batch=80 | 누적 문장 수=7,414
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_80.csv
[경제학] batch=81 | 누적 문장 수=7,493
[경제학] batch=82 | 누적 문장 수=7,612
[경제학] batch=83 | 누적 문장 수=7,697
[경제학] batch=84 | 누적 문장 수=7,806
[경제학] batch=85 | 누적 문장 수=7,874
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_85.csv
[경제학] batch=86 | 누적 문장 수=7,994
[경제학] batch=87 | 누적 문장 수=8,105
[경제학] batch=88 | 누적 문장 수=8,208
[경제학] batch=89 | 누적 문장 수=8,271
[경제학] batch=90 | 누적 문장 수=8,340
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_90.csv
[경제학] batch=91 | 누적 문장 수=8,407
[경제학] batch=92 | 누적 문장 수=8,480
[경제학] batch=93 | 누적 문장 수=8,563
[경제학] batch=94 | 누적 문장 수=8,627
[경제학] batch=95 | 누적 문장 수=8,683
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_95.csv
[경제학] batch=96 | 누적 문장 수=8,747
[경제학] batch=97 | 누적 문장 수=8,815
[경제학] batch=98 | 누적 문장 수=8,920
[경제학] batch=99 | 누적 문장 수=8,990
[경제학] batch=100 | 누적 문장 수=9,084
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_100.csv
[경제학] batch=101 | 누적 문장 수=9,176
[경제학] batch=102 | 누적 문장 수=9,313
[경제학] batch=103 | 누적 문장 수=9,439
[경제학] batch=104 | 누적 문장 수=9,505
[경제학] batch=105 | 누적 문장 수=9,577
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_105.csv
[경제학] batch=106 | 누적 문장 수=9,678
[경제학] batch=107 | 누적 문장 수=9,778
[경제학] batch=108 | 누적 문장 수=9,843
[경제학] batch=109 | 누적 문장 수=9,976
[경제학] batch=110 | 누적 문장 수=10,046
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_110.csv
[경제학] batch=111 | 누적 문장 수=10,104
[경제학] batch=112 | 누적 문장 수=10,163
[경제학] batch=113 | 누적 문장 수=10,251
[경제학] batch=114 | 누적 문장 수=10,318
[경제학] batch=115 | 누적 문장 수=10,388
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_115.csv
[경제학] batch=116 | 누적 문장 수=10,487
[경제학] batch=117 | 누적 문장 수=10,612
[경제학] batch=118 | 누적 문장 수=10,721
[경제학] batch=119 | 누적 문장 수=10,793
[경제학] batch=120 | 누적 문장 수=10,868
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_120.csv
[경제학] batch=121 | 누적 문장 수=10,954
[경제학] batch=122 | 누적 문장 수=11,011
[경제학] batch=123 | 누적 문장 수=11,103
[경제학] batch=124 | 누적 문장 수=11,201
[경제학] batch=125 | 누적 문장 수=11,290
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_125.csv
[경제학] batch=126 | 누적 문장 수=11,362
[경제학] batch=127 | 누적 문장 수=11,451
[경제학] batch=128 | 누적 문장 수=11,565
[경제학] batch=129 | 누적 문장 수=11,677
[경제학] batch=130 | 누적 문장 수=11,734
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_130.csv
[경제학] batch=131 | 누적 문장 수=11,817
[경제학] batch=132 | 누적 문장 수=11,877
[경제학] batch=133 | 누적 문장 수=11,936
[경제학] batch=134 | 누적 문장 수=11,990
[경제학] batch=135 | 누적 문장 수=12,094
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_135.csv
[경제학] batch=136 | 누적 문장 수=12,171
[경제학] batch=137 | 누적 문장 수=12,290
[경제학] batch=138 | 누적 문장 수=12,364
[경제학] batch=139 | 누적 문장 수=12,463
[경제학] batch=140 | 누적 문장 수=12,540
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_140.csv
[경제학] batch=141 | 누적 문장 수=12,614
[경제학] batch=142 | 누적 문장 수=12,747
[경제학] batch=143 | 누적 문장 수=12,872
[경제학] batch=144 | 누적 문장 수=12,928
[경제학] batch=145 | 누적 문장 수=13,022
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_145.csv
[경제학] batch=146 | 누적 문장 수=13,129
[경제학] batch=147 | 누적 문장 수=13,221
[경제학] batch=148 | 누적 문장 수=13,304
[경제학] batch=149 | 누적 문장 수=13,369
[경제학] batch=150 | 누적 문장 수=13,482
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_150.csv
[경제학] batch=151 | 누적 문장 수=13,583
[경제학] batch=152 | 누적 문장 수=13,680
[경제학] batch=153 | 누적 문장 수=13,738
[경제학] batch=154 | 누적 문장 수=13,799
[경제학] batch=155 | 누적 문장 수=13,889
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_155.csv
[경제학] batch=156 | 누적 문장 수=13,965
[경제학] batch=157 | 누적 문장 수=14,037
[경제학] batch=158 | 누적 문장 수=14,106
[경제학] batch=159 | 누적 문장 수=14,213
[경제학] batch=160 | 누적 문장 수=14,271
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_160.csv
[경제학] batch=161 | 누적 문장 수=14,348
[경제학] batch=162 | 누적 문장 수=14,419
[경제학] batch=163 | 누적 문장 수=14,529
[경제학] batch=164 | 누적 문장 수=14,633
[경제학] batch=165 | 누적 문장 수=14,696
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_165.csv
[경제학] batch=166 | 누적 문장 수=14,770
[경제학] batch=167 | 누적 문장 수=14,836
[경제학] batch=168 | 누적 문장 수=14,913
[경제학] batch=169 | 누적 문장 수=15,004
[경제학] batch=170 | 누적 문장 수=15,056
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_170.csv
[경제학] batch=171 | 누적 문장 수=15,117
[경제학] batch=172 | 누적 문장 수=15,208
[경제학] batch=173 | 누적 문장 수=15,305
[경제학] batch=174 | 누적 문장 수=15,388
[경제학] batch=175 | 누적 문장 수=15,483
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_175.csv
[경제학] batch=176 | 누적 문장 수=15,561
[경제학] batch=177 | 누적 문장 수=15,663
[경제학] batch=178 | 누적 문장 수=15,763
[경제학] batch=179 | 누적 문장 수=15,847
[경제학] batch=180 | 누적 문장 수=15,962
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_180.csv
[경제학] batch=181 | 누적 문장 수=16,042
[경제학] batch=182 | 누적 문장 수=16,170
[경제학] batch=183 | 누적 문장 수=16,269
[경제학] batch=184 | 누적 문장 수=16,357
[경제학] batch=185 | 누적 문장 수=16,434
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_185.csv
[경제학] batch=186 | 누적 문장 수=16,514
[경제학] batch=187 | 누적 문장 수=16,636
[경제학] batch=188 | 누적 문장 수=16,744
[경제학] batch=189 | 누적 문장 수=16,838
[경제학] batch=190 | 누적 문장 수=16,958
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_190.csv
[경제학] batch=191 | 누적 문장 수=17,064
[경제학] batch=192 | 누적 문장 수=17,142
[경제학] batch=193 | 누적 문장 수=17,261
[경제학] batch=194 | 누적 문장 수=17,316
[경제학] batch=195 | 누적 문장 수=17,375
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_195.csv
[경제학] batch=196 | 누적 문장 수=17,476
[경제학] batch=197 | 누적 문장 수=17,583
[경제학] batch=198 | 누적 문장 수=17,646
[경제학] batch=199 | 누적 문장 수=17,731
[경제학] batch=200 | 누적 문장 수=17,800
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_200.csv
[경제학] batch=201 | 누적 문장 수=17,858
[경제학] batch=202 | 누적 문장 수=17,920
[경제학] batch=203 | 누적 문장 수=17,991
[경제학] batch=204 | 누적 문장 수=18,047
[경제학] batch=205 | 누적 문장 수=18,109
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_205.csv
[경제학] batch=206 | 누적 문장 수=18,215
[경제학] batch=207 | 누적 문장 수=18,297
[경제학] batch=208 | 누적 문장 수=18,382
[경제학] batch=209 | 누적 문장 수=18,455
[경제학] batch=210 | 누적 문장 수=18,561
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_210.csv
[경제학] batch=211 | 누적 문장 수=18,650
[경제학] batch=212 | 누적 문장 수=18,724
[경제학] batch=213 | 누적 문장 수=18,825
[경제학] batch=214 | 누적 문장 수=18,942
[경제학] batch=215 | 누적 문장 수=19,025
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_215.csv
[경제학] batch=216 | 누적 문장 수=19,117
[경제학] batch=217 | 누적 문장 수=19,182
[경제학] batch=218 | 누적 문장 수=19,280
[경제학] batch=219 | 누적 문장 수=19,347
[경제학] batch=220 | 누적 문장 수=19,453
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_220.csv
[경제학] batch=221 | 누적 문장 수=19,553
[경제학] batch=222 | 누적 문장 수=19,653
[경제학] batch=223 | 누적 문장 수=19,745
[경제학] batch=224 | 누적 문장 수=19,823
[경제학] batch=225 | 누적 문장 수=19,913
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_225.csv
[경제학] batch=226 | 누적 문장 수=20,005
[경제학] batch=227 | 누적 문장 수=20,098
[경제학] batch=228 | 누적 문장 수=20,163
[경제학] batch=229 | 누적 문장 수=20,255
[경제학] batch=230 | 누적 문장 수=20,364
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_230.csv
[경제학] batch=231 | 누적 문장 수=20,492
[경제학] batch=232 | 누적 문장 수=20,567
[경제학] batch=233 | 누적 문장 수=20,620
[경제학] batch=234 | 누적 문장 수=20,718
[경제학] batch=235 | 누적 문장 수=20,781
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_235.csv
[경제학] batch=236 | 누적 문장 수=20,849
[경제학] batch=237 | 누적 문장 수=20,917
[경제학] batch=238 | 누적 문장 수=21,015
[경제학] batch=239 | 누적 문장 수=21,122
[경제학] batch=240 | 누적 문장 수=21,232
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_240.csv
[경제학] batch=241 | 누적 문장 수=21,305
[경제학] batch=242 | 누적 문장 수=21,415
[경제학] batch=243 | 누적 문장 수=21,480
[경제학] batch=244 | 누적 문장 수=21,563
[경제학] batch=245 | 누적 문장 수=21,623
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_245.csv
[경제학] batch=246 | 누적 문장 수=21,729
[경제학] batch=247 | 누적 문장 수=21,785
[경제학] batch=248 | 누적 문장 수=21,885
[경제학] batch=249 | 누적 문장 수=21,988
[경제학] batch=250 | 누적 문장 수=22,062
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_250.csv
[경제학] batch=251 | 누적 문장 수=22,161
[경제학] batch=252 | 누적 문장 수=22,210
[경제학] batch=253 | 누적 문장 수=22,302
[경제학] batch=254 | 누적 문장 수=22,411
[경제학] batch=255 | 누적 문장 수=22,527
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_255.csv
[경제학] batch=256 | 누적 문장 수=22,585
[경제학] batch=257 | 누적 문장 수=22,642
[경제학] batch=258 | 누적 문장 수=22,750
[경제학] batch=259 | 누적 문장 수=22,840
[경제학] batch=260 | 누적 문장 수=22,940
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_260.csv
[경제학] batch=261 | 누적 문장 수=23,005
[경제학] batch=262 | 누적 문장 수=23,071
[경제학] batch=263 | 누적 문장 수=23,150
[경제학] batch=264 | 누적 문장 수=23,264
[경제학] batch=265 | 누적 문장 수=23,341
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_265.csv
[경제학] batch=266 | 누적 문장 수=23,439
[경제학] batch=267 | 누적 문장 수=23,527
[경제학] batch=268 | 누적 문장 수=23,632
[경제학] batch=269 | 누적 문장 수=23,705
[경제학] batch=270 | 누적 문장 수=23,757
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_270.csv
[경제학] batch=271 | 누적 문장 수=23,816
[경제학] batch=272 | 누적 문장 수=23,930
[경제학] batch=273 | 누적 문장 수=24,031
[경제학] batch=274 | 누적 문장 수=24,124
[경제학] batch=275 | 누적 문장 수=24,185
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_275.csv
[경제학] batch=276 | 누적 문장 수=24,271
[경제학] batch=277 | 누적 문장 수=24,380
[경제학] batch=278 | 누적 문장 수=24,435
[경제학] batch=279 | 누적 문장 수=24,490
[경제학] batch=280 | 누적 문장 수=24,587
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_280.csv
[경제학] batch=281 | 누적 문장 수=24,682
[경제학] batch=282 | 누적 문장 수=24,780
[경제학] batch=283 | 누적 문장 수=24,851
[경제학] batch=284 | 누적 문장 수=24,958
[경제학] batch=285 | 누적 문장 수=25,063
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_285.csv
[경제학] batch=286 | 누적 문장 수=25,146
[경제학] batch=287 | 누적 문장 수=25,223
[경제학] batch=288 | 누적 문장 수=25,289
[경제학] batch=289 | 누적 문장 수=25,381
[경제학] batch=290 | 누적 문장 수=25,444
중간 저장 완료 -> ../data/processed/ai\ai_320_temp_until_batch_290.csv
[경제학] batch=291 | 누적 문장 수=25,525

KeyboardInterrupt:

In [8]:
import os
import re
import glob
import pandas as pd

# ==============================
# 설정
# ==============================
DATA_DIR = "../data/processed/ai"   # 네 폴더 경로로 수정
TOPIC_CODE = "320"
TARGET_N = 10000

# ==============================
# 가장 최신 temp csv 찾기
# ==============================
pattern = os.path.join(DATA_DIR, f"ai_{TOPIC_CODE}_temp_until_batch_*.csv")
file_list = glob.glob(pattern)

if not file_list:
    raise FileNotFoundError(f"해당 패턴의 파일이 없음: {pattern}")

def extract_batch_num(filepath):
    filename = os.path.basename(filepath)
    match = re.search(rf"ai_{TOPIC_CODE}_temp_until_batch_(\d+)\.csv$", filename)
    return int(match.group(1)) if match else -1

latest_file = max(file_list, key=extract_batch_num)
latest_batch = extract_batch_num(latest_file)

print(f"가장 최신 temp 파일: {latest_file}")
print(f"batch 번호: {latest_batch}")

# ==============================
# 파일 읽기
# ==============================
df = pd.read_csv(latest_file)

print(f"원본 행 개수: {len(df)}")
print(f"컬럼명: {df.columns.tolist()}")

# ==============================
# 1만 개만 자르기
# ==============================
df_10000 = df.iloc[:TARGET_N].copy()

print(f"최종 사용할 행 개수: {len(df_10000)}")

# ==============================
# 저장
# ==============================
save_path = os.path.join(DATA_DIR, f"ai_{TOPIC_CODE}_final_{TARGET_N}.csv")
df_10000.to_csv(save_path, index=False, encoding="utf-8-sig")

print(f"저장 완료: {save_path}")

가장 최신 temp 파일: ../data/processed/ai\ai_320_temp_until_batch_290.csv
batch 번호: 290
원본 행 개수: 25444
컬럼명: ['text', 'topic_code', 'topic_name', 'source', 'generation_style', 'length_spec', 'temperature', 'batch_num', 'doc_in_batch', 'word_count']
최종 사용할 행 개수: 10000
저장 완료: ../data/processed/ai\ai_320_final_10000.csv

In [9]:
import os
import re
import glob
import pandas as pd

DATA_DIR = "../data/processed/ai"
TOPIC_CODE = "320"
TARGET_N = 10000

pattern = os.path.join(DATA_DIR, f"ai_{TOPIC_CODE}_temp_until_batch_*.csv")
file_list = glob.glob(pattern)

if not file_list:
    raise FileNotFoundError(f"파일이 없음: {pattern}")

def extract_batch_num(filepath):
    filename = os.path.basename(filepath)
    match = re.search(rf"ai_{TOPIC_CODE}_temp_until_batch_(\d+)\.csv$", filename)
    return int(match.group(1)) if match else -1

latest_file = max(file_list, key=extract_batch_num)
df = pd.read_csv(latest_file)

n = len(df)
print(f"최신 파일: {latest_file}")
print(f"현재 데이터 개수: {n}")

if n < TARGET_N:
    print(f"경고: 현재 데이터가 {TARGET_N}개보다 적어서 {n}개만 저장함.")
    df_final = df.copy()
else:
    df_final = df.iloc[:TARGET_N].copy()

save_path = os.path.join(DATA_DIR, f"ai_{TOPIC_CODE}_final_{len(df_final)}.csv")
df_final.to_csv(save_path, index=False, encoding="utf-8-sig")

print(f"저장 완료: {save_path}")

최신 파일: ../data/processed/ai\ai_320_temp_until_batch_290.csv
현재 데이터 개수: 25444
저장 완료: ../data/processed/ai\ai_320_final_10000.csv

In [11]:
# print(df_final.head())
print(df_final.isnull().sum())
print("중복 행 수:", df_final.duplicated().sum())

text                0
topic_code          0
topic_name          0
source              0
generation_style    0
length_spec         0
temperature         0
batch_num           0
doc_in_batch        0
word_count          0
dtype: int64
중복 행 수: 0

## 병렬처리 이후 코드

In [10]:
import os
import re
import time
import random
import pandas as pd
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor, as_completed

# =========================================================
# 0. OpenAI client
# =========================================================
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [11]:
# =========================================================
# 1. 기본 설정
# =========================================================
MODEL_NAME = "gpt-5.4-mini"
RANDOM_STATE = 42
random.seed(RANDOM_STATE)

TARGET_PER_TOPIC = 10_000
BATCH_DOCS = 20
SAVE_EVERY = 5

OUTPUT_DIR = "../data/processed/ai"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 병렬 처리 수
MAX_WORKERS = 4   # 처음엔 4로 시작, 괜찮으면 6 정도까지 시도

topic_info = {
    "320": {
        "topic_name": "경제학",
        "prompt_topic": "경제학 개념, 시장, 정책, 소비, 생산, 분배, 금융, 경기 등과 관련된 설명형 글"
    },
    "360": {
        "topic_name": "법률·법학",
        "prompt_topic": "법, 제도, 권리, 의무, 판례, 책임, 절차, 규범 등과 관련된 설명형 글"
    },
    "370": {
        "topic_name": "교육학",
        "prompt_topic": "학습, 교육과정, 교수법, 평가, 학교, 발달, 교육환경 등과 관련된 설명형 글"
    },
    "400": {
        "topic_name": "자연과학",
        "prompt_topic": "자연 현상, 생명, 물질, 에너지, 실험, 관찰, 과학 원리 등과 관련된 설명형 글"
    },
    "440": {
        "topic_name": "천문학",
        "prompt_topic": "우주, 행성, 별, 은하, 중력, 천체 관측, 우주 현상 등과 관련된 설명형 글"
    },
}

STYLE_POOL = [
    "개념 설명 중심",
    "원리 설명 중심",
    "사례를 곁들인 설명",
    "비교·대조 중심",
    "입문서 스타일의 설명",
]

LENGTH_POOL = [
    "4~6문장",
    "5~7문장",
    "6~8문장",
]

TEMPERATURE_POOL = [0.7, 0.9, 1.0]

In [12]:
# =========================================================
# 2. 텍스트 처리 함수
# =========================================================

def normalize_text(text):
    if text is None:
        return ""
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    text = text.replace("“", '"').replace("”", '"').replace("’", "'").replace("‘", "'")
    return text

def split_sentences_korean(text):
    text = normalize_text(text)
    text = text.replace("\n", " ")
    sents = re.split(r'(?<=[\.\?\!])\s+', text)

    if len(sents) == 1:
        sents = re.split(r'(?<=다)\s+|(?<=요)\s+|(?<=니다)\s+', text)

    return [s.strip() for s in sents if s.strip()]

def is_valid_sentence(text, min_words=5, max_words=50):
    text = normalize_text(text)

    if not text:
        return False
    if len(text) < 10:
        return False
    if not re.search(r"[가-힣]", text):
        return False

    word_count = len(text.split())
    if word_count < min_words or word_count > max_words:
        return False

    hangul_chars = re.findall(r"[가-힣]", text)
    if len(hangul_chars) / max(len(text), 1) < 0.3:
        return False

    meta_patterns = [
        r"^제\s*\d+\s*장",
        r"^제\s*\d+\s*절",
        r"^\d+\.$",
        r"^\d+\)",
        r"^부록",
        r"^참고문헌",
        r"^목차",
        r"^저자",
        r"^출판사",
        r"^ISBN",
        r"^머리말",
        r"^서문",
        r"^차례",
    ]
    for pattern in meta_patterns:
        if re.search(pattern, text):
            return False

    return True

def clean_ai_sentences(sentences):
    cleaned = []
    seen = set()

    for sent in sentences:
        sent = normalize_text(sent)
        sent = re.sub(r'^\s*[-•\d\.\)\(]+\s*', '', sent).strip()

        if is_valid_sentence(sent):
            if sent not in seen:
                cleaned.append(sent)
                seen.add(sent)

    return cleaned

In [13]:
# =========================================================
# 3. 프롬프트 및 생성 함수
# =========================================================

def make_generation_prompt(topic_name, topic_desc, style, length_spec, batch_docs):
    prompt = f"""
다음 조건에 맞는 한국어 설명문 여러 개를 작성하시오.

[분야]
{topic_name}

[세부 주제 범위]
{topic_desc}

[문체]
- 자연스러운 설명문 형태
- 지나치게 문학적이거나 대화체인 문장은 피할 것
- 불필요한 제목이나 메모는 쓰지 말 것
- 동일 표현 반복을 피할 것

[스타일]
{style}

[길이]
각 글은 {length_spec}

[출력 형식]
- 서로 다른 짧은 글 {batch_docs}개를 생성할 것
- 각 글은 1, 2, 3 ... 번호를 붙여 구분할 것
- 각 글은 하나의 짧은 문단 형태로 작성할 것
- 반드시 한국어만 사용할 것
"""
    return prompt.strip()

def generate_batch_text(topic_name, topic_desc, batch_docs=BATCH_DOCS):
    style = random.choice(STYLE_POOL)
    length_spec = random.choice(LENGTH_POOL)
    temperature = random.choice(TEMPERATURE_POOL)

    prompt = make_generation_prompt(
        topic_name=topic_name,
        topic_desc=topic_desc,
        style=style,
        length_spec=length_spec,
        batch_docs=batch_docs
    )

    response = client.responses.create(
        model=MODEL_NAME,
        input=prompt,
        temperature=temperature
    )

    text = getattr(response, "output_text", None)
    if not text:
        raise ValueError("응답에서 output_text를 찾지 못했다.")

    return text, {
        "style": style,
        "length_spec": length_spec,
        "temperature": temperature
    }

def split_generated_documents(raw_text):
    raw_text = normalize_text(raw_text)
    parts = re.split(r'\s*(?=\d+\.\s)', raw_text)

    docs = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        part = re.sub(r'^\d+\.\s*', '', part).strip()
        if part:
            docs.append(part)

    if len(docs) <= 1:
        docs = [x.strip() for x in raw_text.split("\n") if x.strip()]

    return docs

In [14]:
# =========================================================
# 4. 저장 파일명 함수
# =========================================================

def get_temp_save_path(topic_code, batch_num):
    return os.path.join(OUTPUT_DIR, f"ai_{topic_code}_temp_until_batch_{batch_num}.csv")

def get_final_save_path(topic_code, target_n):
    return os.path.join(OUTPUT_DIR, f"ai_{topic_code}_final_{target_n}.csv")

In [15]:
# =========================================================
# 5. 배치 1개 처리 함수 (병렬 실행용)
# =========================================================

def process_single_batch(topic_code, batch_num, batch_docs=BATCH_DOCS, max_retries=3):
    topic_name = topic_info[topic_code]["topic_name"]
    topic_desc = topic_info[topic_code]["prompt_topic"]

    for attempt in range(1, max_retries + 1):
        try:
            raw_text, meta = generate_batch_text(topic_name, topic_desc, batch_docs=batch_docs)
            docs = split_generated_documents(raw_text)

            batch_rows = []

            for doc_idx, doc in enumerate(docs, start=1):
                sentences = split_sentences_korean(doc)
                cleaned_sents = clean_ai_sentences(sentences)

                for sent in cleaned_sents:
                    batch_rows.append({
                        "text": sent,
                        "topic_code": topic_code,
                        "topic_name": topic_name,
                        "source": "ai",
                        "generation_style": meta["style"],
                        "length_spec": meta["length_spec"],
                        "temperature": meta["temperature"],
                        "batch_num": batch_num,
                        "doc_in_batch": doc_idx,
                        "word_count": len(sent.split())
                    })

            return batch_num, batch_rows, None

        except Exception as e:
            if attempt == max_retries:
                return batch_num, [], str(e)
            time.sleep(2 * attempt)

In [16]:
# =========================================================
# 6. 주제 하나 실행 (병렬 버전)
# =========================================================

def build_ai_topic_dataset_parallel(topic_code, target_n=10_000, save_every=5, batch_docs=BATCH_DOCS, max_workers=4):
    topic_name = topic_info[topic_code]["topic_name"]

    print(f"\n===== {topic_name} ({topic_code}) AI 데이터 생성 시작 =====")

    all_rows = []
    seen_sentences = set()

    submitted_batch_num = 0
    completed_batch_num = 0

    futures = {}

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        while len(all_rows) < target_n:
            while len(futures) < max_workers:
                submitted_batch_num += 1
                future = executor.submit(process_single_batch, topic_code, submitted_batch_num, batch_docs)
                futures[future] = submitted_batch_num

            for future in as_completed(list(futures.keys())):
                batch_num = futures.pop(future)

                try:
                    returned_batch_num, batch_rows, error_msg = future.result()

                    if error_msg is not None:
                        print(f"[오류] {topic_name} batch={returned_batch_num}, error={error_msg}")
                    else:
                        new_count = 0
                        for row in batch_rows:
                            sent = row["text"]
                            if sent not in seen_sentences:
                                all_rows.append(row)
                                seen_sentences.add(sent)
                                new_count += 1

                        completed_batch_num += 1
                        print(f"[{topic_name}] batch={returned_batch_num} | 추가 문장 수={new_count} | 누적 문장 수={len(all_rows):,}")

                        if completed_batch_num % save_every == 0:
                            temp_df = pd.DataFrame(all_rows)
                            temp_path = get_temp_save_path(topic_code, completed_batch_num)
                            temp_df.to_csv(temp_path, index=False, encoding="utf-8-sig")
                            print(f"중간 저장 완료 -> {temp_path}")

                    if len(all_rows) >= target_n:
                        break

                    submitted_batch_num += 1
                    new_future = executor.submit(process_single_batch, topic_code, submitted_batch_num, batch_docs)
                    futures[new_future] = submitted_batch_num

                except Exception as e:
                    print(f"[예상치 못한 오류] batch={batch_num}, error={e}")

                if len(all_rows) >= target_n:
                    break

    final_df = pd.DataFrame(all_rows).drop_duplicates(subset=["text"]).reset_index(drop=True)
    final_df = final_df.head(target_n).copy()

    final_path = get_final_save_path(topic_code, target_n)
    final_df.to_csv(final_path, index=False, encoding="utf-8-sig")

    print(f"===== {topic_name} 최종 완료: {len(final_df):,}문장 =====")
    print(f"최종 저장 완료 -> {final_path}")

    return final_df

In [17]:
# =========================================================
# 7. 실행 (주제별 개별 실행)
# =========================================================

In [18]:
# 360: 법률·법학
df_ai_360 = build_ai_topic_dataset_parallel(
    topic_code="360",
    target_n=TARGET_PER_TOPIC,
    save_every=SAVE_EVERY,
    batch_docs=BATCH_DOCS,
    max_workers=MAX_WORKERS
)

===== 법률·법학 (360) AI 데이터 생성 시작 =====
[법률·법학] batch=1 | 추가 문장 수=80 | 누적 문장 수=80
[법률·법학] batch=3 | 추가 문장 수=120 | 누적 문장 수=200
[법률·법학] batch=2 | 추가 문장 수=79 | 누적 문장 수=279
[법률·법학] batch=4 | 추가 문장 수=78 | 누적 문장 수=357
[법률·법학] batch=5 | 추가 문장 수=80 | 누적 문장 수=437
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_5.csv
[법률·법학] batch=7 | 추가 문장 수=119 | 누적 문장 수=556
[법률·법학] batch=6 | 추가 문장 수=119 | 누적 문장 수=675
[법률·법학] batch=8 | 추가 문장 수=98 | 누적 문장 수=773
[법률·법학] batch=10 | 추가 문장 수=79 | 누적 문장 수=852
[법률·법학] batch=11 | 추가 문장 수=100 | 누적 문장 수=952
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_10.csv
[법률·법학] batch=9 | 추가 문장 수=120 | 누적 문장 수=1,072
[법률·법학] batch=12 | 추가 문장 수=77 | 누적 문장 수=1,149
[법률·법학] batch=13 | 추가 문장 수=79 | 누적 문장 수=1,228
[법률·법학] batch=15 | 추가 문장 수=119 | 누적 문장 수=1,347
[법률·법학] batch=14 | 추가 문장 수=119 | 누적 문장 수=1,466
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_15.csv
[법률·법학] batch=16 | 추가 문장 수=76 | 누적 문장 수=1,542
[법률·법학] batch=17 | 추가 문장 수=120 | 누적 문장 수=1,662
[법률·법학] batch=18 | 추가 문장 수=98 | 누적 문장 수=1,760
[법률·법학] batch=19 | 추가 문장 수=117 | 누적 문장 수=1,877
[법률·법학] batch=20 | 추가 문장 수=117 | 누적 문장 수=1,994
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_20.csv
[법률·법학] batch=22 | 추가 문장 수=99 | 누적 문장 수=2,093
[법률·법학] batch=21 | 추가 문장 수=80 | 누적 문장 수=2,173
[법률·법학] batch=23 | 추가 문장 수=120 | 누적 문장 수=2,293
[법률·법학] batch=24 | 추가 문장 수=118 | 누적 문장 수=2,411
[법률·법학] batch=25 | 추가 문장 수=114 | 누적 문장 수=2,525
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_25.csv
[법률·법학] batch=26 | 추가 문장 수=116 | 누적 문장 수=2,641
[법률·법학] batch=27 | 추가 문장 수=120 | 누적 문장 수=2,761
[법률·법학] batch=28 | 추가 문장 수=78 | 누적 문장 수=2,839
[법률·법학] batch=30 | 추가 문장 수=76 | 누적 문장 수=2,915
[법률·법학] batch=31 | 추가 문장 수=80 | 누적 문장 수=2,995
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_30.csv
[법률·법학] batch=29 | 추가 문장 수=100 | 누적 문장 수=3,095
[법률·법학] batch=32 | 추가 문장 수=93 | 누적 문장 수=3,188
[법률·법학] batch=33 | 추가 문장 수=79 | 누적 문장 수=3,267
[법률·법학] batch=35 | 추가 문장 수=118 | 누적 문장 수=3,385
[법률·법학] batch=34 | 추가 문장 수=118 | 누적 문장 수=3,503
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_35.csv
[법률·법학] batch=36 | 추가 문장 수=119 | 누적 문장 수=3,622
[법률·법학] batch=37 | 추가 문장 수=98 | 누적 문장 수=3,720
[법률·법학] batch=39 | 추가 문장 수=95 | 누적 문장 수=3,815
[법률·법학] batch=38 | 추가 문장 수=117 | 누적 문장 수=3,932
[법률·법학] batch=40 | 추가 문장 수=95 | 누적 문장 수=4,027
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_40.csv
[법률·법학] batch=43 | 추가 문장 수=77 | 누적 문장 수=4,104
[법률·법학] batch=42 | 추가 문장 수=118 | 누적 문장 수=4,222
[법률·법학] batch=41 | 추가 문장 수=120 | 누적 문장 수=4,342
[법률·법학] batch=44 | 추가 문장 수=112 | 누적 문장 수=4,454
[법률·법학] batch=46 | 추가 문장 수=100 | 누적 문장 수=4,554
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_45.csv
[법률·법학] batch=45 | 추가 문장 수=120 | 누적 문장 수=4,674
[법률·법학] batch=47 | 추가 문장 수=119 | 누적 문장 수=4,793
[법률·법학] batch=48 | 추가 문장 수=80 | 누적 문장 수=4,873
[법률·법학] batch=51 | 추가 문장 수=91 | 누적 문장 수=4,964
[법률·법학] batch=50 | 추가 문장 수=119 | 누적 문장 수=5,083
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_50.csv
[법률·법학] batch=49 | 추가 문장 수=116 | 누적 문장 수=5,199
[법률·법학] batch=52 | 추가 문장 수=91 | 누적 문장 수=5,290
[법률·법학] batch=54 | 추가 문장 수=78 | 누적 문장 수=5,368
[법률·법학] batch=53 | 추가 문장 수=118 | 누적 문장 수=5,486
[법률·법학] batch=55 | 추가 문장 수=118 | 누적 문장 수=5,604
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_55.csv
[법률·법학] batch=56 | 추가 문장 수=70 | 누적 문장 수=5,674
[법률·법학] batch=57 | 추가 문장 수=80 | 누적 문장 수=5,754
[법률·법학] batch=58 | 추가 문장 수=77 | 누적 문장 수=5,831
[법률·법학] batch=59 | 추가 문장 수=99 | 누적 문장 수=5,930
[법률·법학] batch=60 | 추가 문장 수=97 | 누적 문장 수=6,027
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_60.csv
[법률·법학] batch=61 | 추가 문장 수=76 | 누적 문장 수=6,103
[법률·법학] batch=62 | 추가 문장 수=74 | 누적 문장 수=6,177
[법률·법학] batch=63 | 추가 문장 수=80 | 누적 문장 수=6,257
[법률·법학] batch=64 | 추가 문장 수=73 | 누적 문장 수=6,330
[법률·법학] batch=65 | 추가 문장 수=120 | 누적 문장 수=6,450
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_65.csv
[법률·법학] batch=66 | 추가 문장 수=119 | 누적 문장 수=6,569
[법률·법학] batch=67 | 추가 문장 수=80 | 누적 문장 수=6,649
[법률·법학] batch=68 | 추가 문장 수=118 | 누적 문장 수=6,767
[법률·법학] batch=69 | 추가 문장 수=120 | 누적 문장 수=6,887
[법률·법학] batch=71 | 추가 문장 수=80 | 누적 문장 수=6,967
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_70.csv
[법률·법학] batch=70 | 추가 문장 수=99 | 누적 문장 수=7,066
[법률·법학] batch=72 | 추가 문장 수=78 | 누적 문장 수=7,144
[법률·법학] batch=75 | 추가 문장 수=75 | 누적 문장 수=7,219
[법률·법학] batch=76 | 추가 문장 수=72 | 누적 문장 수=7,291
[법률·법학] batch=73 | 추가 문장 수=132 | 누적 문장 수=7,423
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_75.csv
[법률·법학] batch=74 | 추가 문장 수=115 | 누적 문장 수=7,538
[법률·법학] batch=78 | 추가 문장 수=72 | 누적 문장 수=7,610
[법률·법학] batch=77 | 추가 문장 수=95 | 누적 문장 수=7,705
[법률·법학] batch=79 | 추가 문장 수=79 | 누적 문장 수=7,784
[법률·법학] batch=80 | 추가 문장 수=112 | 누적 문장 수=7,896
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_80.csv
[법률·법학] batch=81 | 추가 문장 수=88 | 누적 문장 수=7,984
[법률·법학] batch=83 | 추가 문장 수=72 | 누적 문장 수=8,056
[법률·법학] batch=82 | 추가 문장 수=100 | 누적 문장 수=8,156
[법률·법학] batch=84 | 추가 문장 수=98 | 누적 문장 수=8,254
[법률·법학] batch=85 | 추가 문장 수=99 | 누적 문장 수=8,353
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_85.csv
[법률·법학] batch=87 | 추가 문장 수=70 | 누적 문장 수=8,423
[법률·법학] batch=86 | 추가 문장 수=114 | 누적 문장 수=8,537
[법률·법학] batch=88 | 추가 문장 수=78 | 누적 문장 수=8,615
[법률·법학] batch=89 | 추가 문장 수=75 | 누적 문장 수=8,690
[법률·법학] batch=90 | 추가 문장 수=79 | 누적 문장 수=8,769
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_90.csv
[법률·법학] batch=92 | 추가 문장 수=69 | 누적 문장 수=8,838
[법률·법학] batch=91 | 추가 문장 수=99 | 누적 문장 수=8,937
[법률·법학] batch=93 | 추가 문장 수=78 | 누적 문장 수=9,015
[법률·법학] batch=94 | 추가 문장 수=70 | 누적 문장 수=9,085
[법률·법학] batch=95 | 추가 문장 수=74 | 누적 문장 수=9,159
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_95.csv
[법률·법학] batch=96 | 추가 문장 수=100 | 누적 문장 수=9,259
[법률·법학] batch=97 | 추가 문장 수=80 | 누적 문장 수=9,339
[법률·법학] batch=98 | 추가 문장 수=80 | 누적 문장 수=9,419
[법률·법학] batch=99 | 추가 문장 수=98 | 누적 문장 수=9,517
[법률·법학] batch=100 | 추가 문장 수=119 | 누적 문장 수=9,636
중간 저장 완료 -> ../data/processed/ai\ai_360_temp_until_batch_100.csv
[법률·법학] batch=101 | 추가 문장 수=112 | 누적 문장 수=9,748
[법률·법학] batch=102 | 추가 문장 수=80 | 누적 문장 수=9,828
[법률·법학] batch=103 | 추가 문장 수=80 | 누적 문장 수=9,908
[법률·법학] batch=104 | 추가 문장 수=109 | 누적 문장 수=10,017
===== 법률·법학 최종 완료: 10,000문장 =====
최종 저장 완료 -> ../data/processed/ai\ai_360_final_10000.csv

In [19]:
# 370: 교육학
df_ai_370 = build_ai_topic_dataset_parallel(
    topic_code="370",
    target_n=TARGET_PER_TOPIC,
    save_every=SAVE_EVERY,
    batch_docs=BATCH_DOCS,
    max_workers=MAX_WORKERS
)

===== 교육학 (370) AI 데이터 생성 시작 =====
[교육학] batch=3 | 추가 문장 수=80 | 누적 문장 수=80
[교육학] batch=2 | 추가 문장 수=80 | 누적 문장 수=160
[교육학] batch=1 | 추가 문장 수=80 | 누적 문장 수=240
[교육학] batch=4 | 추가 문장 수=100 | 누적 문장 수=340
[교육학] batch=5 | 추가 문장 수=80 | 누적 문장 수=420
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_5.csv
[교육학] batch=6 | 추가 문장 수=79 | 누적 문장 수=499
[교육학] batch=7 | 추가 문장 수=99 | 누적 문장 수=598
[교육학] batch=8 | 추가 문장 수=119 | 누적 문장 수=717
[교육학] batch=10 | 추가 문장 수=80 | 누적 문장 수=797
[교육학] batch=9 | 추가 문장 수=99 | 누적 문장 수=896
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_10.csv
[교육학] batch=11 | 추가 문장 수=81 | 누적 문장 수=977
[교육학] batch=12 | 추가 문장 수=100 | 누적 문장 수=1,077
[교육학] batch=13 | 추가 문장 수=77 | 누적 문장 수=1,154
[교육학] batch=14 | 추가 문장 수=119 | 누적 문장 수=1,273
[교육학] batch=15 | 추가 문장 수=120 | 누적 문장 수=1,393
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_15.csv
[교육학] batch=16 | 추가 문장 수=97 | 누적 문장 수=1,490
[교육학] batch=17 | 추가 문장 수=80 | 누적 문장 수=1,570
[교육학] batch=18 | 추가 문장 수=99 | 누적 문장 수=1,669
[교육학] batch=19 | 추가 문장 수=120 | 누적 문장 수=1,789
[교육학] batch=20 | 추가 문장 수=118 | 누적 문장 수=1,907
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_20.csv
[교육학] batch=21 | 추가 문장 수=78 | 누적 문장 수=1,985
[교육학] batch=22 | 추가 문장 수=95 | 누적 문장 수=2,080
[교육학] batch=23 | 추가 문장 수=74 | 누적 문장 수=2,154
[교육학] batch=24 | 추가 문장 수=80 | 누적 문장 수=2,234
[교육학] batch=25 | 추가 문장 수=78 | 누적 문장 수=2,312
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_25.csv
[교육학] batch=26 | 추가 문장 수=119 | 누적 문장 수=2,431
[교육학] batch=27 | 추가 문장 수=77 | 누적 문장 수=2,508
[교육학] batch=28 | 추가 문장 수=120 | 누적 문장 수=2,628
[교육학] batch=29 | 추가 문장 수=78 | 누적 문장 수=2,706
[교육학] batch=30 | 추가 문장 수=99 | 누적 문장 수=2,805
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_30.csv
[교육학] batch=31 | 추가 문장 수=98 | 누적 문장 수=2,903
[교육학] batch=32 | 추가 문장 수=80 | 누적 문장 수=2,983
[교육학] batch=35 | 추가 문장 수=77 | 누적 문장 수=3,060
[교육학] batch=33 | 추가 문장 수=120 | 누적 문장 수=3,180
[교육학] batch=34 | 추가 문장 수=135 | 누적 문장 수=3,315
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_35.csv
[교육학] batch=36 | 추가 문장 수=120 | 누적 문장 수=3,435
[교육학] batch=38 | 추가 문장 수=96 | 누적 문장 수=3,531
[교육학] batch=39 | 추가 문장 수=96 | 누적 문장 수=3,627
[교육학] batch=37 | 추가 문장 수=120 | 누적 문장 수=3,747
[교육학] batch=40 | 추가 문장 수=99 | 누적 문장 수=3,846
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_40.csv
[교육학] batch=41 | 추가 문장 수=118 | 누적 문장 수=3,964
[교육학] batch=43 | 추가 문장 수=114 | 누적 문장 수=4,078
[교육학] batch=42 | 추가 문장 수=119 | 누적 문장 수=4,197
[교육학] batch=44 | 추가 문장 수=79 | 누적 문장 수=4,276
[교육학] batch=45 | 추가 문장 수=82 | 누적 문장 수=4,358
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_45.csv
[교육학] batch=47 | 추가 문장 수=95 | 누적 문장 수=4,453
[교육학] batch=46 | 추가 문장 수=100 | 누적 문장 수=4,553
[교육학] batch=48 | 추가 문장 수=95 | 누적 문장 수=4,648
[교육학] batch=49 | 추가 문장 수=79 | 누적 문장 수=4,727
[교육학] batch=51 | 추가 문장 수=78 | 누적 문장 수=4,805
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_50.csv
[교육학] batch=50 | 추가 문장 수=99 | 누적 문장 수=4,904
[교육학] batch=52 | 추가 문장 수=95 | 누적 문장 수=4,999
[교육학] batch=53 | 추가 문장 수=77 | 누적 문장 수=5,076
[교육학] batch=56 | 추가 문장 수=77 | 누적 문장 수=5,153
[교육학] batch=54 | 추가 문장 수=116 | 누적 문장 수=5,269
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_55.csv
[교육학] batch=55 | 추가 문장 수=120 | 누적 문장 수=5,389
[교육학] batch=57 | 추가 문장 수=76 | 누적 문장 수=5,465
[교육학] batch=58 | 추가 문장 수=77 | 누적 문장 수=5,542
[교육학] batch=59 | 추가 문장 수=97 | 누적 문장 수=5,639
[교육학] batch=60 | 추가 문장 수=99 | 누적 문장 수=5,738
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_60.csv
[교육학] batch=61 | 추가 문장 수=79 | 누적 문장 수=5,817
[교육학] batch=62 | 추가 문장 수=73 | 누적 문장 수=5,890
[교육학] batch=63 | 추가 문장 수=117 | 누적 문장 수=6,007
[교육학] batch=64 | 추가 문장 수=117 | 누적 문장 수=6,124
[교육학] batch=65 | 추가 문장 수=95 | 누적 문장 수=6,219
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_65.csv
[교육학] batch=66 | 추가 문장 수=120 | 누적 문장 수=6,339
[교육학] batch=67 | 추가 문장 수=94 | 누적 문장 수=6,433
[교육학] batch=68 | 추가 문장 수=119 | 누적 문장 수=6,552
[교육학] batch=69 | 추가 문장 수=94 | 누적 문장 수=6,646
[교육학] batch=71 | 추가 문장 수=117 | 누적 문장 수=6,763
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_70.csv
[교육학] batch=72 | 추가 문장 수=94 | 누적 문장 수=6,857
[교육학] batch=70 | 추가 문장 수=97 | 누적 문장 수=6,954
[교육학] batch=74 | 추가 문장 수=119 | 누적 문장 수=7,073
[교육학] batch=75 | 추가 문장 수=97 | 누적 문장 수=7,170
[교육학] batch=73 | 추가 문장 수=140 | 누적 문장 수=7,310
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_75.csv
[교육학] batch=76 | 추가 문장 수=94 | 누적 문장 수=7,404
[교육학] batch=78 | 추가 문장 수=119 | 누적 문장 수=7,523
[교육학] batch=77 | 추가 문장 수=96 | 누적 문장 수=7,619
[교육학] batch=79 | 추가 문장 수=99 | 누적 문장 수=7,718
[교육학] batch=80 | 추가 문장 수=114 | 누적 문장 수=7,832
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_80.csv
[교육학] batch=83 | 추가 문장 수=92 | 누적 문장 수=7,924
[교육학] batch=81 | 추가 문장 수=110 | 누적 문장 수=8,034
[교육학] batch=82 | 추가 문장 수=119 | 누적 문장 수=8,153
[교육학] batch=84 | 추가 문장 수=118 | 누적 문장 수=8,271
[교육학] batch=85 | 추가 문장 수=76 | 누적 문장 수=8,347
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_85.csv
[교육학] batch=86 | 추가 문장 수=73 | 누적 문장 수=8,420
[교육학] batch=88 | 추가 문장 수=99 | 누적 문장 수=8,519
[교육학] batch=87 | 추가 문장 수=120 | 누적 문장 수=8,639
[교육학] batch=90 | 추가 문장 수=99 | 누적 문장 수=8,738
[교육학] batch=89 | 추가 문장 수=78 | 누적 문장 수=8,816
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_90.csv
[교육학] batch=91 | 추가 문장 수=76 | 누적 문장 수=8,892
[교육학] batch=92 | 추가 문장 수=76 | 누적 문장 수=8,968
[교육학] batch=95 | 추가 문장 수=71 | 누적 문장 수=9,039
[교육학] batch=93 | 추가 문장 수=76 | 누적 문장 수=9,115
[교육학] batch=94 | 추가 문장 수=94 | 누적 문장 수=9,209
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_95.csv
[교육학] batch=96 | 추가 문장 수=80 | 누적 문장 수=9,289
[교육학] batch=99 | 추가 문장 수=92 | 누적 문장 수=9,381
[교육학] batch=98 | 추가 문장 수=96 | 누적 문장 수=9,477
[교육학] batch=97 | 추가 문장 수=118 | 누적 문장 수=9,595
[교육학] batch=100 | 추가 문장 수=80 | 누적 문장 수=9,675
중간 저장 완료 -> ../data/processed/ai\ai_370_temp_until_batch_100.csv
[교육학] batch=103 | 추가 문장 수=96 | 누적 문장 수=9,771
[교육학] batch=101 | 추가 문장 수=100 | 누적 문장 수=9,871
[교육학] batch=102 | 추가 문장 수=115 | 누적 문장 수=9,986
[교육학] batch=104 | 추가 문장 수=93 | 누적 문장 수=10,079
===== 교육학 최종 완료: 10,000문장 =====
최종 저장 완료 -> ../data/processed/ai\ai_370_final_10000.csv

In [20]:
# 400: 자연과학
df_ai_400 = build_ai_topic_dataset_parallel(
    topic_code="400",
    target_n=TARGET_PER_TOPIC,
    save_every=SAVE_EVERY,
    batch_docs=BATCH_DOCS,
    max_workers=MAX_WORKERS
)

===== 자연과학 (400) AI 데이터 생성 시작 =====
[자연과학] batch=1 | 추가 문장 수=79 | 누적 문장 수=79
[자연과학] batch=3 | 추가 문장 수=80 | 누적 문장 수=159
[자연과학] batch=4 | 추가 문장 수=100 | 누적 문장 수=259
[자연과학] batch=2 | 추가 문장 수=137 | 누적 문장 수=396
[자연과학] batch=5 | 추가 문장 수=99 | 누적 문장 수=495
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_5.csv
[자연과학] batch=6 | 추가 문장 수=99 | 누적 문장 수=594
[자연과학] batch=7 | 추가 문장 수=140 | 누적 문장 수=734
[자연과학] batch=8 | 추가 문장 수=96 | 누적 문장 수=830
[자연과학] batch=9 | 추가 문장 수=99 | 누적 문장 수=929
[자연과학] batch=10 | 추가 문장 수=100 | 누적 문장 수=1,029
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_10.csv
[자연과학] batch=11 | 추가 문장 수=118 | 누적 문장 수=1,147
[자연과학] batch=12 | 추가 문장 수=78 | 누적 문장 수=1,225
[자연과학] batch=14 | 추가 문장 수=100 | 누적 문장 수=1,325
[자연과학] batch=13 | 추가 문장 수=99 | 누적 문장 수=1,424
[자연과학] batch=15 | 추가 문장 수=140 | 누적 문장 수=1,564
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_15.csv
[자연과학] batch=16 | 추가 문장 수=77 | 누적 문장 수=1,641
[자연과학] batch=17 | 추가 문장 수=73 | 누적 문장 수=1,714
[자연과학] batch=19 | 추가 문장 수=75 | 누적 문장 수=1,789
[자연과학] batch=18 | 추가 문장 수=114 | 누적 문장 수=1,903
[자연과학] batch=20 | 추가 문장 수=79 | 누적 문장 수=1,982
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_20.csv
[자연과학] batch=21 | 추가 문장 수=78 | 누적 문장 수=2,060
[자연과학] batch=22 | 추가 문장 수=99 | 누적 문장 수=2,159
[자연과학] batch=23 | 추가 문장 수=98 | 누적 문장 수=2,257
[자연과학] batch=24 | 추가 문장 수=98 | 누적 문장 수=2,355
[자연과학] batch=25 | 추가 문장 수=72 | 누적 문장 수=2,427
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_25.csv
[자연과학] batch=27 | 추가 문장 수=91 | 누적 문장 수=2,518
[자연과학] batch=26 | 추가 문장 수=118 | 누적 문장 수=2,636
[자연과학] batch=28 | 추가 문장 수=111 | 누적 문장 수=2,747
[자연과학] batch=29 | 추가 문장 수=73 | 누적 문장 수=2,820
[자연과학] batch=31 | 추가 문장 수=77 | 누적 문장 수=2,897
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_30.csv
[자연과학] batch=30 | 추가 문장 수=111 | 누적 문장 수=3,008
[자연과학] batch=32 | 추가 문장 수=107 | 누적 문장 수=3,115
[자연과학] batch=33 | 추가 문장 수=118 | 누적 문장 수=3,233
[자연과학] batch=34 | 추가 문장 수=75 | 누적 문장 수=3,308
[자연과학] batch=35 | 추가 문장 수=114 | 누적 문장 수=3,422
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_35.csv
[자연과학] batch=36 | 추가 문장 수=74 | 누적 문장 수=3,496
[자연과학] batch=37 | 추가 문장 수=109 | 누적 문장 수=3,605
[자연과학] batch=39 | 추가 문장 수=95 | 누적 문장 수=3,700
[자연과학] batch=38 | 추가 문장 수=112 | 누적 문장 수=3,812
[자연과학] batch=40 | 추가 문장 수=74 | 누적 문장 수=3,886
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_40.csv
[자연과학] batch=41 | 추가 문장 수=72 | 누적 문장 수=3,958
[자연과학] batch=43 | 추가 문장 수=113 | 누적 문장 수=4,071
[자연과학] batch=42 | 추가 문장 수=115 | 누적 문장 수=4,186
[자연과학] batch=44 | 추가 문장 수=113 | 누적 문장 수=4,299
[자연과학] batch=45 | 추가 문장 수=78 | 누적 문장 수=4,377
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_45.csv
[자연과학] batch=46 | 추가 문장 수=70 | 누적 문장 수=4,447
[자연과학] batch=47 | 추가 문장 수=77 | 누적 문장 수=4,524
[자연과학] batch=48 | 추가 문장 수=113 | 누적 문장 수=4,637
[자연과학] batch=49 | 추가 문장 수=103 | 누적 문장 수=4,740
[자연과학] batch=50 | 추가 문장 수=115 | 누적 문장 수=4,855
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_50.csv
[자연과학] batch=51 | 추가 문장 수=106 | 누적 문장 수=4,961
[자연과학] batch=52 | 추가 문장 수=100 | 누적 문장 수=5,061
[자연과학] batch=54 | 추가 문장 수=74 | 누적 문장 수=5,135
[자연과학] batch=53 | 추가 문장 수=91 | 누적 문장 수=5,226
[자연과학] batch=55 | 추가 문장 수=79 | 누적 문장 수=5,305
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_55.csv
[자연과학] batch=56 | 추가 문장 수=115 | 누적 문장 수=5,420
[자연과학] batch=58 | 추가 문장 수=99 | 누적 문장 수=5,519
[자연과학] batch=57 | 추가 문장 수=95 | 누적 문장 수=5,614
[자연과학] batch=59 | 추가 문장 수=73 | 누적 문장 수=5,687
[자연과학] batch=60 | 추가 문장 수=114 | 누적 문장 수=5,801
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_60.csv
[자연과학] batch=63 | 추가 문장 수=73 | 누적 문장 수=5,874
[자연과학] batch=62 | 추가 문장 수=70 | 누적 문장 수=5,944
[자연과학] batch=61 | 추가 문장 수=115 | 누적 문장 수=6,059
[자연과학] batch=64 | 추가 문장 수=100 | 누적 문장 수=6,159
[자연과학] batch=67 | 추가 문장 수=83 | 누적 문장 수=6,242
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_65.csv
[자연과학] batch=66 | 추가 문장 수=98 | 누적 문장 수=6,340
[자연과학] batch=65 | 추가 문장 수=113 | 누적 문장 수=6,453
[자연과학] batch=68 | 추가 문장 수=118 | 누적 문장 수=6,571
[자연과학] batch=69 | 추가 문장 수=109 | 누적 문장 수=6,680
[자연과학] batch=71 | 추가 문장 수=94 | 누적 문장 수=6,774
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_70.csv
[자연과학] batch=70 | 추가 문장 수=92 | 누적 문장 수=6,866
[자연과학] batch=72 | 추가 문장 수=86 | 누적 문장 수=6,952
[자연과학] batch=73 | 추가 문장 수=93 | 누적 문장 수=7,045
[자연과학] batch=75 | 추가 문장 수=86 | 누적 문장 수=7,131
[자연과학] batch=74 | 추가 문장 수=68 | 누적 문장 수=7,199
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_75.csv
[자연과학] batch=76 | 추가 문장 수=110 | 누적 문장 수=7,309
[자연과학] batch=78 | 추가 문장 수=96 | 누적 문장 수=7,405
[자연과학] batch=77 | 추가 문장 수=69 | 누적 문장 수=7,474
[자연과학] batch=79 | 추가 문장 수=110 | 누적 문장 수=7,584
[자연과학] batch=80 | 추가 문장 수=68 | 누적 문장 수=7,652
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_80.csv
[자연과학] batch=83 | 추가 문장 수=71 | 누적 문장 수=7,723
[자연과학] batch=82 | 추가 문장 수=86 | 누적 문장 수=7,809
[자연과학] batch=81 | 추가 문장 수=93 | 누적 문장 수=7,902
[자연과학] batch=84 | 추가 문장 수=69 | 누적 문장 수=7,971
[자연과학] batch=86 | 추가 문장 수=78 | 누적 문장 수=8,049
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_85.csv
[자연과학] batch=85 | 추가 문장 수=107 | 누적 문장 수=8,156
[자연과학] batch=87 | 추가 문장 수=90 | 누적 문장 수=8,246
[자연과학] batch=88 | 추가 문장 수=99 | 누적 문장 수=8,345
[자연과학] batch=89 | 추가 문장 수=76 | 누적 문장 수=8,421
[자연과학] batch=90 | 추가 문장 수=72 | 누적 문장 수=8,493
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_90.csv
[자연과학] batch=91 | 추가 문장 수=96 | 누적 문장 수=8,589
[자연과학] batch=92 | 추가 문장 수=106 | 누적 문장 수=8,695
[자연과학] batch=95 | 추가 문장 수=66 | 누적 문장 수=8,761
[자연과학] batch=93 | 추가 문장 수=61 | 누적 문장 수=8,822
[자연과학] batch=94 | 추가 문장 수=83 | 누적 문장 수=8,905
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_95.csv
[자연과학] batch=96 | 추가 문장 수=117 | 누적 문장 수=9,022
[자연과학] batch=98 | 추가 문장 수=97 | 누적 문장 수=9,119
[자연과학] batch=97 | 추가 문장 수=73 | 누적 문장 수=9,192
[자연과학] batch=99 | 추가 문장 수=125 | 누적 문장 수=9,317
[자연과학] batch=100 | 추가 문장 수=105 | 누적 문장 수=9,422
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_100.csv
[자연과학] batch=102 | 추가 문장 수=65 | 누적 문장 수=9,487
[자연과학] batch=103 | 추가 문장 수=90 | 누적 문장 수=9,577
[자연과학] batch=101 | 추가 문장 수=106 | 누적 문장 수=9,683
[자연과학] batch=104 | 추가 문장 수=62 | 누적 문장 수=9,745
[자연과학] batch=106 | 추가 문장 수=69 | 누적 문장 수=9,814
중간 저장 완료 -> ../data/processed/ai\ai_400_temp_until_batch_105.csv
[자연과학] batch=105 | 추가 문장 수=110 | 누적 문장 수=9,924
[자연과학] batch=108 | 추가 문장 수=94 | 누적 문장 수=10,018
===== 자연과학 최종 완료: 10,000문장 =====
최종 저장 완료 -> ../data/processed/ai\ai_400_final_10000.csv

In [21]:
# 440: 천문학
df_ai_440 = build_ai_topic_dataset_parallel(
    topic_code="440",
    target_n=TARGET_PER_TOPIC,
    save_every=SAVE_EVERY,
    batch_docs=BATCH_DOCS,
    max_workers=MAX_WORKERS
)

===== 천문학 (440) AI 데이터 생성 시작 =====
[천문학] batch=4 | 추가 문장 수=80 | 누적 문장 수=80
[천문학] batch=3 | 추가 문장 수=100 | 누적 문장 수=180
[천문학] batch=1 | 추가 문장 수=120 | 누적 문장 수=300
[천문학] batch=2 | 추가 문장 수=137 | 누적 문장 수=437
[천문학] batch=5 | 추가 문장 수=99 | 누적 문장 수=536
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_5.csv
[천문학] batch=6 | 추가 문장 수=77 | 누적 문장 수=613
[천문학] batch=8 | 추가 문장 수=99 | 누적 문장 수=712
[천문학] batch=7 | 추가 문장 수=120 | 누적 문장 수=832
[천문학] batch=9 | 추가 문장 수=98 | 누적 문장 수=930
[천문학] batch=10 | 추가 문장 수=116 | 누적 문장 수=1,046
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_10.csv
[천문학] batch=12 | 추가 문장 수=100 | 누적 문장 수=1,146
[천문학] batch=11 | 추가 문장 수=119 | 누적 문장 수=1,265
[천문학] batch=13 | 추가 문장 수=79 | 누적 문장 수=1,344
[천문학] batch=15 | 추가 문장 수=78 | 누적 문장 수=1,422
[천문학] batch=14 | 추가 문장 수=134 | 누적 문장 수=1,556
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_15.csv
[천문학] batch=16 | 추가 문장 수=118 | 누적 문장 수=1,674
[천문학] batch=17 | 추가 문장 수=118 | 누적 문장 수=1,792
[천문학] batch=18 | 추가 문장 수=99 | 누적 문장 수=1,891
[천문학] batch=19 | 추가 문장 수=100 | 누적 문장 수=1,991
[천문학] batch=20 | 추가 문장 수=95 | 누적 문장 수=2,086
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_20.csv
[천문학] batch=21 | 추가 문장 수=79 | 누적 문장 수=2,165
[천문학] batch=24 | 추가 문장 수=98 | 누적 문장 수=2,263
[천문학] batch=23 | 추가 문장 수=137 | 누적 문장 수=2,400
[천문학] batch=22 | 추가 문장 수=95 | 누적 문장 수=2,495
[천문학] batch=27 | 추가 문장 수=79 | 누적 문장 수=2,574
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_25.csv
[천문학] batch=26 | 추가 문장 수=119 | 누적 문장 수=2,693
[천문학] batch=25 | 추가 문장 수=100 | 누적 문장 수=2,793
[천문학] batch=28 | 추가 문장 수=100 | 누적 문장 수=2,893
[천문학] batch=30 | 추가 문장 수=92 | 누적 문장 수=2,985
[천문학] batch=31 | 추가 문장 수=77 | 누적 문장 수=3,062
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_30.csv
[천문학] batch=32 | 추가 문장 수=117 | 누적 문장 수=3,179
[천문학] batch=29 | 추가 문장 수=120 | 누적 문장 수=3,299
[천문학] batch=33 | 추가 문장 수=79 | 누적 문장 수=3,378
[천문학] batch=34 | 추가 문장 수=116 | 누적 문장 수=3,494
[천문학] batch=35 | 추가 문장 수=100 | 누적 문장 수=3,594
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_35.csv
[천문학] batch=36 | 추가 문장 수=79 | 누적 문장 수=3,673
[천문학] batch=37 | 추가 문장 수=78 | 누적 문장 수=3,751
[천문학] batch=38 | 추가 문장 수=98 | 누적 문장 수=3,849
[천문학] batch=39 | 추가 문장 수=116 | 누적 문장 수=3,965
[천문학] batch=40 | 추가 문장 수=71 | 누적 문장 수=4,036
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_40.csv
[천문학] batch=41 | 추가 문장 수=80 | 누적 문장 수=4,116
[천문학] batch=42 | 추가 문장 수=97 | 누적 문장 수=4,213
[천문학] batch=44 | 추가 문장 수=98 | 누적 문장 수=4,311
[천문학] batch=43 | 추가 문장 수=119 | 누적 문장 수=4,430
[천문학] batch=45 | 추가 문장 수=80 | 누적 문장 수=4,510
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_45.csv
[천문학] batch=46 | 추가 문장 수=75 | 누적 문장 수=4,585
[천문학] batch=48 | 추가 문장 수=75 | 누적 문장 수=4,660
[천문학] batch=47 | 추가 문장 수=117 | 누적 문장 수=4,777
[천문학] batch=50 | 추가 문장 수=77 | 누적 문장 수=4,854
[천문학] batch=49 | 추가 문장 수=99 | 누적 문장 수=4,953
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_50.csv
[천문학] batch=52 | 추가 문장 수=79 | 누적 문장 수=5,032
[천문학] batch=51 | 추가 문장 수=118 | 누적 문장 수=5,150
[천문학] batch=53 | 추가 문장 수=93 | 누적 문장 수=5,243
[천문학] batch=54 | 추가 문장 수=114 | 누적 문장 수=5,357
[천문학] batch=55 | 추가 문장 수=100 | 누적 문장 수=5,457
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_55.csv
[천문학] batch=56 | 추가 문장 수=113 | 누적 문장 수=5,570
[천문학] batch=57 | 추가 문장 수=90 | 누적 문장 수=5,660
[천문학] batch=58 | 추가 문장 수=78 | 누적 문장 수=5,738
[천문학] batch=59 | 추가 문장 수=141 | 누적 문장 수=5,879
[천문학] batch=60 | 추가 문장 수=137 | 누적 문장 수=6,016
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_60.csv
[천문학] batch=62 | 추가 문장 수=137 | 누적 문장 수=6,153
[천문학] batch=61 | 추가 문장 수=97 | 누적 문장 수=6,250
[천문학] batch=63 | 추가 문장 수=74 | 누적 문장 수=6,324
[천문학] batch=64 | 추가 문장 수=113 | 누적 문장 수=6,437
[천문학] batch=65 | 추가 문장 수=112 | 누적 문장 수=6,549
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_65.csv
[천문학] batch=66 | 추가 문장 수=120 | 누적 문장 수=6,669
[천문학] batch=67 | 추가 문장 수=93 | 누적 문장 수=6,762
[천문학] batch=68 | 추가 문장 수=114 | 누적 문장 수=6,876
[천문학] batch=69 | 추가 문장 수=120 | 누적 문장 수=6,996
[천문학] batch=71 | 추가 문장 수=98 | 누적 문장 수=7,094
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_70.csv
[천문학] batch=72 | 추가 문장 수=119 | 누적 문장 수=7,213
[천문학] batch=70 | 추가 문장 수=138 | 누적 문장 수=7,351
[천문학] batch=74 | 추가 문장 수=79 | 누적 문장 수=7,430
[천문학] batch=75 | 추가 문장 수=86 | 누적 문장 수=7,516
[천문학] batch=73 | 추가 문장 수=71 | 누적 문장 수=7,587
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_75.csv
[천문학] batch=76 | 추가 문장 수=88 | 누적 문장 수=7,675
[천문학] batch=77 | 추가 문장 수=69 | 누적 문장 수=7,744
[천문학] batch=78 | 추가 문장 수=80 | 누적 문장 수=7,824
[천문학] batch=79 | 추가 문장 수=100 | 누적 문장 수=7,924
[천문학] batch=80 | 추가 문장 수=79 | 누적 문장 수=8,003
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_80.csv
[천문학] batch=82 | 추가 문장 수=73 | 누적 문장 수=8,076
[천문학] batch=83 | 추가 문장 수=112 | 누적 문장 수=8,188
[천문학] batch=81 | 추가 문장 수=133 | 누적 문장 수=8,321
[천문학] batch=84 | 추가 문장 수=118 | 누적 문장 수=8,439
[천문학] batch=85 | 추가 문장 수=117 | 누적 문장 수=8,556
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_85.csv
[천문학] batch=86 | 추가 문장 수=95 | 누적 문장 수=8,651
[천문학] batch=87 | 추가 문장 수=97 | 누적 문장 수=8,748
[천문학] batch=88 | 추가 문장 수=92 | 누적 문장 수=8,840
[천문학] batch=89 | 추가 문장 수=72 | 누적 문장 수=8,912
[천문학] batch=91 | 추가 문장 수=120 | 누적 문장 수=9,032
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_90.csv
[천문학] batch=92 | 추가 문장 수=98 | 누적 문장 수=9,130
[천문학] batch=90 | 추가 문장 수=99 | 누적 문장 수=9,229
[천문학] batch=93 | 추가 문장 수=98 | 누적 문장 수=9,327
[천문학] batch=94 | 추가 문장 수=69 | 누적 문장 수=9,396
[천문학] batch=95 | 추가 문장 수=89 | 누적 문장 수=9,485
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_95.csv
[천문학] batch=96 | 추가 문장 수=138 | 누적 문장 수=9,623
[천문학] batch=97 | 추가 문장 수=109 | 누적 문장 수=9,732
[천문학] batch=99 | 추가 문장 수=112 | 누적 문장 수=9,844
[천문학] batch=98 | 추가 문장 수=78 | 누적 문장 수=9,922
[천문학] batch=100 | 추가 문장 수=99 | 누적 문장 수=10,021
중간 저장 완료 -> ../data/processed/ai\ai_440_temp_until_batch_100.csv
===== 천문학 최종 완료: 10,000문장 =====
최종 저장 완료 -> ../data/processed/ai\ai_440_final_10000.csv

In [27]:
# =========================================================
# 8. 전체 통합 저장 (320 포함, 총 5만개)
# =========================================================

path_ai_320 = os.path.join(OUTPUT_DIR, "ai_320_final_10000.csv")
df_ai_320 = pd.read_csv(path_ai_320)

ai_all_df = pd.concat(
    [df_ai_320, df_ai_360, df_ai_370, df_ai_400, df_ai_440],
    axis=0
).reset_index(drop=True)

before_dedup = len(ai_all_df)
ai_all_df = ai_all_df.drop_duplicates(subset=["text"]).reset_index(drop=True)
after_dedup = len(ai_all_df)

print(f"중복 제거 전 문장 수: {before_dedup:,}")
print(f"중복 제거 후 문장 수: {after_dedup:,}")

if after_dedup < 50000:
    print("주의: 중복 제거 후 5만 개보다 적다.")
else:
    ai_all_df = ai_all_df.head(50000).copy()

ai_all_path = os.path.join(OUTPUT_DIR, "ai_5topics_final_50000.csv")
ai_all_df.to_csv(ai_all_path, index=False, encoding="utf-8-sig")

print(f"\n전체 통합 저장 완료 -> {ai_all_path}")
print(f"전체 문장 수: {len(ai_all_df):,}")

중복 제거 전 문장 수: 50,000
중복 제거 후 문장 수: 49,989
주의: 중복 제거 후 5만 개보다 적다.

전체 통합 저장 완료 -> ../data/processed/ai\ai_5topics_final_50000.csv
전체 문장 수: 49,989

In [35]:
import os
import time
import pandas as pd

FINAL_PATH = os.path.join(OUTPUT_DIR, "ai_5topics_final_50000.csv")

# 현재 파일 다시 읽기
ai_all_df = pd.read_csv(FINAL_PATH)

existing_texts = set(ai_all_df["text"].astype(str).tolist())
current_count_440 = (ai_all_df["topic_code"].astype(str) == "440").sum()
needed = 10000 - current_count_440

print("현재 전체 개수:", len(ai_all_df))
print("현재 440 개수:", current_count_440)
print("추가 필요 개수:", needed)

new_rows = []
extra_batch_num = 999999

topic_code = "440"
topic_name = topic_info[topic_code]["topic_name"]
topic_desc = topic_info[topic_code]["prompt_topic"]

while needed > 0:
    try:
        raw_text, meta = generate_batch_text(
            topic_name=topic_name,
            topic_desc=topic_desc,
            batch_docs=BATCH_DOCS
        )

        docs = split_generated_documents(raw_text)

        for doc_idx, doc in enumerate(docs, start=1):
            sentences = split_sentences_korean(doc)
            cleaned_sents = clean_ai_sentences(sentences)

            for sent in cleaned_sents:
                if sent not in existing_texts:
                    new_rows.append({
                        "text": sent,
                        "topic_code": topic_code,
                        "topic_name": topic_name,
                        "source": "ai",
                        "generation_style": meta["style"],
                        "length_spec": meta["length_spec"],
                        "temperature": meta["temperature"],
                        "batch_num": extra_batch_num,
                        "doc_in_batch": doc_idx,
                        "word_count": len(sent.split())
                    })
                    existing_texts.add(sent)
                    needed -= 1

                    if needed <= 0:
                        break
            if needed <= 0:
                break

        print("남은 부족분:", needed)
        extra_batch_num += 1
        time.sleep(0.8)

    except Exception as e:
        print("오류:", e)
        time.sleep(3)

if new_rows:
    ai_all_df = pd.concat([ai_all_df, pd.DataFrame(new_rows)], axis=0).reset_index(drop=True)
    ai_all_df = ai_all_df.drop_duplicates(subset=["text"]).reset_index(drop=True)

# 저장
ai_all_df.to_csv(FINAL_PATH, index=False, encoding="utf-8-sig")

# 검증
df_check = pd.read_csv(FINAL_PATH)
print("\n저장 후 전체 개수:", len(df_check))
print("저장 후 주제별 개수:")
print(df_check["topic_code"].astype(str).value_counts().sort_index())
print("저장 후 중복 개수:", df_check.duplicated(subset=["text"]).sum())

현재 전체 개수: 49989
현재 440 개수: 9989
추가 필요 개수: 11
남은 부족분: 0

저장 후 전체 개수: 50000
저장 후 주제별 개수:
topic_code
320    10000
360    10000
370    10000
400    10000
440    10000
Name: count, dtype: int64
저장 후 중복 개수: 0

In [36]:
import os
import pandas as pd

FINAL_PATH = os.path.join(OUTPUT_DIR, "ai_5topics_final_50000.csv")

# 불러오기
df_final = pd.read_csv(FINAL_PATH)

# =========================================================
# 1. 전체 개수 확인
# =========================================================
print("전체 개수:", len(df_final))

# =========================================================
# 2. 주제별 개수 확인
# =========================================================
print("\n주제별 개수:")
topic_counts = df_final["topic_code"].astype(str).value_counts().sort_index()
print(topic_counts)

# =========================================================
# 3. 중복 확인
# =========================================================
dup_count = df_final.duplicated(subset=["text"]).sum()
print("\n중복 개수:", dup_count)

# =========================================================
# 4. 데이터프레임 구조 확인
# =========================================================
print("\n컬럼:")
print(df_final.columns)

# =========================================================
# 5. 혹시 모를 이상치 체크 (선택)
# =========================================================
assert len(df_final) == 50000, "❌ 전체 개수 틀림"
assert all(topic_counts == 10000), "❌ 주제별 개수 틀림"
assert dup_count == 0, "❌ 중복 존재"

print("\n🔥 최종 데이터셋 정상 완료")

전체 개수: 50000

주제별 개수:
topic_code
320    10000
360    10000
370    10000
400    10000
440    10000
Name: count, dtype: int64

중복 개수: 0

컬럼:
Index(['text', 'topic_code', 'topic_name', 'source', 'generation_style',
       'length_spec', 'temperature', 'batch_num', 'doc_in_batch',
       'word_count'],
      dtype='object')

🔥 최종 데이터셋 정상 완료

## 최종 데이터 합치기

In [1]:
import os
import pandas as pd

# 1. 파일 경로
human_path = "../data/processed/human/human_5topics_50k.csv"
ai_path = "../data/processed/ai/ai_5topics_final_50000.csv"

# 2. 데이터 불러오기
human_all_df = pd.read_csv(human_path)
ai_all_df = pd.read_csv(ai_path)

print("HUMAN shape:", human_all_df.shape)
print("AI shape:", ai_all_df.shape)

# 3. source 컬럼 확인 및 통일
human_all_df["source"] = "human"
ai_all_df["source"] = "ai"

# 4. AI 데이터에 length_bin 없으면 생성
if "length_bin" not in ai_all_df.columns:
    bins = [5, 10, 15, 20, 30, 51]
    labels = ["5-9", "10-14", "15-19", "20-29", "30-50"]
    ai_all_df["length_bin"] = pd.cut(
        ai_all_df["word_count"],
        bins=bins,
        labels=labels,
        right=False,
        include_lowest=True
    )

# 5. 필요한 컬럼만 정리
required_cols = ["text", "word_count", "length_bin", "topic_code", "topic_name", "source"]

human_all_df = human_all_df[required_cols].copy()
ai_all_df = ai_all_df[required_cols].copy()

# topic_code 형식 통일
human_all_df["topic_code"] = human_all_df["topic_code"].astype(str)
ai_all_df["topic_code"] = ai_all_df["topic_code"].astype(str)

# 6. 최종 통합
final_df = pd.concat([human_all_df, ai_all_df], axis=0).reset_index(drop=True)

# 7. 저장
save_path = "../data/final/final_human_ai_100k.csv"
final_df.to_csv(save_path, index=False, encoding="utf-8-sig")

HUMAN shape: (50000, 6)
AI shape: (50000, 10)

In [46]:
# 8. 확인 출력
print("\n최종 저장 완료 ->", save_path)
print("최종 shape:", final_df.shape)

최종 저장 완료 -> ../data/final/final_human_ai_100k.csv
최종 shape: (100000, 6)

In [47]:
print("\n[source 분포]")
print(final_df["source"].value_counts())

[source 분포]
source
human    50000
ai       50000
Name: count, dtype: int64

In [48]:
print("\n[topic_name 분포]")
print(final_df["topic_name"].value_counts())

[topic_name 분포]
topic_name
경제학      20000
법률·법학    20000
교육학      20000
자연과학     20000
천문학      20000
Name: count, dtype: int64

In [3]:
# source x topic_name 분포
final_df.groupby(["source", "topic_name"]).size()

source  topic_name
ai      경제학           10000
        교육학           10000
        법률·법학         10000
        자연과학          10000
        천문학           10000
human   경제학           10000
        교육학           10000
        법률·법학         10000
        자연과학          10000
        천문학           10000
dtype: int64

In [5]:
final_df.groupby("source")["word_count"].describe()

          count      mean       std  min  25%   50%   75%   max
source
ai      50000.0  10.43092  2.593485  5.0  9.0  10.0  12.0  25.0
human   50000.0  13.47154  7.059064  5.0  8.0  12.0  17.0  50.0

In [51]:
print("\n전체 text 중복 수:", final_df["text"].duplicated().sum())

전체 text 중복 수: 0

In [4]:
final_df

,text,word_count,length_bin,topic_code,topic_name,source
0,그러면서 기술과 자본이 어우러져 만들어내는 생산력이 19세기 패권 경쟁에서 가장 중...,13,10-14,320,경제학,human
1,그렇다면 차를 살 때도 약간의 수고를 감수하고 바지런을 떠는 게 더 좋지 않을까.,13,10-14,320,경제학,human
2,그 마음으로 여러분만의 '사이드 프로젝트'를 시작하세요.,6,5-9,320,경제학,human
3,그러나 나는 입사해서 지금까지 매일 받는 봉사료를 모아서 생활비로 쓰고 있다.,11,10-14,320,경제학,human
4,"'사회운동노조주의'는 노조 스스로 정치적으로 강화돼야 한다고 하지만, 그것이 어떤 ...",11,10-14,320,경제학,human
...,...,...,...,...,...,...
99995,"행성은 별 주위를 공전하는 천체로, 스스로 빛을 내지 않는다는 점이 별과 다릅니다.",12,10-14,440,천문학,ai
99996,지구처럼 표면에 물이 존재할 수 있는 행성은 생명체가 살 수 있는 환경과도 연결되어...,15,15-19,440,천문학,ai
99997,예를 들어 화성은 과거에 물이 흐른 흔적이 발견되어 오랫동안 연구 대상이 되어 왔습니다.,13,10-14,440,천문학,ai
99998,"목성은 거대한 가스 행성으로, 강한 중력 때문에 수많은 위성을 거느립니다.",10,10-14,440,천문학,ai
99999,행성의 크기와 조성은 생성 과정과 밀접한 관련이 있습니다.,8,5-9,440,천문학,ai